include:
  - project: dau/ci/pyci
    file: .gitlab-ci-template.yml

### Jobs templates ###

.base:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_ID
  image: gitlab-registry.esrf.fr/dau/ci/pyci/python_3.9_node_18:latest
  tags:
    - linux
  timeout: 10m

.pnpm-base:
  extends: .base
  variables:
    CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/.cypress-cache/"
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
      - .cypress-cache

.pnpm-base-build:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  stage: build
  extends: .pnpm-base

.deploy:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  stage: deploy
  extends: .base

### Required jobs ###

lint:
  stage: style
  needs: []
  extends: .pnpm-base
  script:
    - pnpm run lint

test:
  image: cypress/base:18.16.0
  stage: test
  extends: .pnpm-base
  needs: []
  timeout: 15m
  before_script:
    # https://github.com/cypress-io/cypress-docker-images/issues/642 and https://github.com/cypress-io/cypress-docker-images/issues/649
    - apt-get update && apt-get install curl -y
    - apt-get install python3 python3-pip -y
    - !reference [.pnpm-base, before_script]
  script:
    - python3 --version
    - python3 -m pip install --upgrade pip
    - python3 -m pip install --upgrade setuptools
    - python3 -m pip install -e .
    - pnpm build
    - ewoksweb --config ./pysrc/ewoksweb/tests/resources/config.py &
    # Try to connect to server for 20s. If not, `timeout` will return non-zero so the CI fails.
    - timeout 20s bash -c "while ! curl http://127.0.0.1:8000 -m1 -o/dev/null -s;do sleep 0.3;done"
    # https://github.com/vercel/serve/issues/751
    - pnpm preview &
    - timeout 20s bash -c "while ! curl http://127.0.0.1:3000 -m1 -o/dev/null -s;do sleep 0.3;done"
    - pnpm cypress:run

build-package:
  extends: .pnpm-base-build
  script:
    - python3 --version
    - python3 -m pip install --upgrade pip setuptools
    - pnpm build:package
    - !reference [.build_sdist, script]
  after_script:
    - !reference [.build_sdist, after_script]
  artifacts: # Cannot use !reference [.build_sdist, artifacts] since it is unsupported: https://gitlab.com/gitlab-org/gitlab/-/issues/351169
    paths:
      - sdist/
    when: on_success
    expire_in: 2h

pages:
  stage: deploy
  variables:
    VITE_SERVER_URL: https://bosquet.silx.org
    VITE_SERVER_API_SUFFIX: /ewoks/api
    VITE_ROUTER_BASE_DIR: /ewoks/ewoksweb/
  extends: .pnpm-base-build
  script:
    - pnpm build:pages
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
    when: on_success
    expire_in: 2h

assets:
  extends: .assets

release_pypi:
  extends: .pypi

testpypi:
  extends: .testpypi
