stages:
  - test
  - style
  - build
  - deploy

### Jobs templates ###

.base:
  image: 'docker-registry.esrf.fr/dau/ewoks:python_3.9_node_16'
  tags:
    - linux
  only:
    refs:
      - main
      - merge_requests
  timeout: 10m

.pnpm-base:
  extends: .base
  variables:
    CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/.cypress-cache/'
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
      - .cypress-cache

.pnpm-base-build:
  stage: build
  extends: .pnpm-base
  only:
    refs:
      - main

.deploy:
  stage: deploy
  extends: .base
  only:
    refs:
      - main

### Required jobs ###

flake8:
  stage: style
  needs: []
  extends: .base
  before_script:
    - python3 -m pip install flake8
  script:
    - flake8

black:
  stage: style
  needs: []
  extends: .base
  before_script:
    - python3 -m pip install black
  script:
    - LC_ALL=C.UTF-8 black --check --safe .

lint:
  stage: style
  needs: []
  extends: .pnpm-base
  script:
    - pnpm run lint

test:
  image: cypress/base:16.18.0
  stage: test
  extends: .pnpm-base
  needs: []
  timeout: 15m
  before_script:
    # https://github.com/cypress-io/cypress-docker-images/issues/642 and https://github.com/cypress-io/cypress-docker-images/issues/649
    - apt-get update && apt-get install curl -y
    - apt-get install python3 python3-pip -y
    - !reference [.pnpm-base, before_script]
  script:
    - python3 --version
    - python3 -m pip install --upgrade pip
    - python3 -m pip install --upgrade setuptools
    - python3 -m pip install ewoksserver
    - python3 -m pip install --upgrade --pre ewoksserver
    - ewoks-server -p 5000 -c ./pysrc/ewoksweb/tests/resources/config.py &
    - pnpm build
    # Try to connect to server for 10s. If not, `timeout` will return non-zero so the CI fails.
    - timeout 10s bash -c "while ! curl http://127.0.0.1:5000 -m1 -o/dev/null -s;do sleep 0.3;done"
    # https://github.com/vercel/serve/issues/751
    - pnpm dlx serve@13.0.4 --no-port-switching -s build -l 3000 &
    - timeout 10s bash -c "while ! curl http://127.0.0.1:3000 -m1 -o/dev/null -s;do sleep 0.3;done"
    - pnpm cypress:run

build-package:
  extends: .pnpm-base-build
  script:
    - python3 --version
    - python3 -m pip install --upgrade pip
    - python3 -m pip install --upgrade setuptools
    - pnpm build:package
    - python3 setup.py sdist
    - mv dist sdist
  after_script:
    - ls -Rl sdist
  artifacts:
    paths:
      - sdist/
    when: on_success
    expire_in: 2h

pages:
  stage: deploy
  variables:
    VITE_SERVER_URL: https://bosquet.silx.org/ewoks/
    VITE_ROUTER_BASE_DIR: ewoks/ewoksweb/
  extends: .pnpm-base-build
  script:
    - pnpm build:pages
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
    when: on_success
    expire_in: 2h

assets:
  extends: .deploy
  script:
    - rm -rf assets
    - mkdir assets
    - mv sdist/* assets/
  after_script:
    - ls -Rl assets
  artifacts:
    paths:
      - assets
    when: on_success
    expire_in: 2h
