stages:
  - style
  - build
  - deploy

### Jobs templates for each stage ###

.base:
  image: "docker-registry.esrf.fr/dau/ewoks:node_12"
  tags:
    - linux
  only:
    refs:
      - main
      - merge_requests
  timeout: 10m

.style:
  stage: style
  extends: .base

.build:
  stage: build
  extends: .base
  before_script:
    - rm -rf ${ARTIFACTS_DEST}
  after_script:
    - mv ${ARTIFACTS_SOURCE} ${ARTIFACTS_DEST}
  artifacts:
    paths:
      - ${ARTIFACTS_DEST}/
    when: on_success
    expire_in: 2h
  only:
    refs:
      - main

.deploy:
  stage: deploy
  extends: .base
  tags:
    - linux
  only:
    refs:
      - main

### Required jobs ###

flake8:
  extends: .style
  before_script:
    - python3 -m pip install flake8
  script:
    - flake8

.black: # needs upgrade python 3.5 to 3.8
  extends: .style
  before_script:
    - python3 -m pip install black
  script:
    - LC_ALL=C.UTF-8 black --check --safe .

lint:
  extends: .style
  before_script:
    # - npx -y browserslist@latest --update-db
    - npm install -y
  script:
    - npm run lint

build:
  extends: .build
  stage: build
  before_script:
    # - npx -y browserslist@latest --update-db
    - npm install -y
  script:
    - npm run build
    - python3 setup.py sdist
  variables:
    ARTIFACTS_SOURCE: dist
    ARTIFACTS_DEST: sdist

assets:
  extends: .deploy
  script:
    - rm -rf assets
    - mkdir assets
    - mv sdist/* assets/
  after_script:
    - ls -Rl assets
  artifacts:
    paths:
      - assets
    when: on_success
    expire_in: 2h
