name: Release

on:
  workflow_dispatch:
    inputs:
      use-test-pypi:
        type: boolean
        description: Whether the release should go to TestPyPI instead of PyPI

jobs:
  # Build Python package
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v6

      - name: Install
        uses: ./.github/actions/install

      - name: Build front-end 📦
        run: pnpm build:package

      - name: Build Python package 🐍
        run: |
          - pip install --pre build
          - python -m build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          name: dist
          path: dist/

  # Publish package to TestPyPI
  publish-testpypi:
    needs: build
    if: ${{ github.event.inputs.use-test-pypi == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: ewoks-kit/.github/.github/actions/setup-python-package@main
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  # Publish package to PyPI
  publish-pypi:
    needs: build
    if: ${{ github.event.inputs.use-test-pypi == 'false' }}
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: ewoks-kit/.github/.github/actions/setup-python-package@main

      - name: Release on PyPI 🎉
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Tag release 🏷️
        uses: ewoks-kit/.github/.github/actions/tag-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
